language: cpp

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_C_COMPILER="${X_CC}" -DCMAKE_CXX_COMPILER="${X_CXX}" -Dc10k-build_tests=ON ..

script:
    - make VERBOSE=1 -j4
    - ctest --output-on-failure && valgrind --leak-check=full ctest --output-on-failure

matrix:
  include:
    - env: 
          - X_CC=gcc-4.9
          - X_CXX=g++-4.9
          - BUILD_TYPE=Debug
    - env: 
          - X_CC=gcc-4.9
          - X_CXX=g++-4.9
          - BUILD_TYPE=Release
    - env: 
          - X_CC=gcc-5
          - X_CXX=g++-5
          - BUILD_TYPE=Debug
    - env: 
          - X_CC=gcc-5
          - X_CXX=g++-5
          - BUILD_TYPE=Release
    - env: 
          - X_CC=clang-3.8
          - X_CXX=clang++-3.8
          - BUILD_TYPE=Debug
    - env:
          - X_CC=clang-3.8
          - X_CXX=clang++-3.8
          - BUILD_TYPE=Release

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
        packages:
            - clang-3.8
            - g++-4.9
            - g++-5
            - cmake
            - cmake-data
            - build-essential
            - valgrind
